# Generated by Django 2.1.2 on 2018-11-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181119_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='isManage',
            field=models.IntegerField(default=1, verbose_name='是否管理者'),
        ),
    ]
