# Generated by Django 2.1.2 on 2018-12-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181119_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isManage',
        ),
    ]
