# Generated by Django 2.1.2 on 2018-11-13 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depart', '0002_department_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('content_json', models.TextField(verbose_name='参数表')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='depart.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '参数表',
                'verbose_name_plural': '参数表',
            },
        ),
    ]
