# Generated by Django 2.1.2 on 2018-12-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('para', '0002_auto_20181211_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para',
            name='content_json',
            field=models.TextField(blank=True, null=True, verbose_name='参数表'),
        ),
    ]
