# Generated by Django 2.1.2 on 2018-11-13 14:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_name', models.CharField(max_length=50, verbose_name='绩效名称')),
                ('self_evaluat', models.TextField(verbose_name='自评得分')),
                ('second_evaluat', models.TextField(verbose_name='二次评价得分')),
                ('status', models.IntegerField(verbose_name='审批进度')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '绩效考核表',
                'verbose_name_plural': '绩效考核表',
            },
        ),
    ]
