# Generated by Django 2.1.2 on 2018-11-13 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
