# Generated by Django 2.1.2 on 2018-12-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0004_auto_20181127_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
